##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########


## Set up some global variables for property substitution in ANY stage
globalVariables:
  THISTAG: "v2"
  THISCOMMAND: "rollbacktargeted"
  THISLOGLEVEL: "INFO"
  LOGSDIRNAME: "mdclogfiles"
  LOGDIRLOC: "."  
  LOGBASE: "allcmds-${THISLOGLEVEL}"
  LOGEXTENSION: "log"
  CHANGELOGBASE: "changelog.mdc"


# do some stages 
stages:


  ## A stage of actions. 
  MakeLogFile01:
    ## set up vars for property substitution in THIS stage only
    stageVariables:
      CHANGELOGEXTRA: "cafe"
      CHANGELOGEXT: "sql"
      CHANGELOGFILE: "${CHANGELOGBASE}-${CHANGELOGEXTRA}.${CHANGELOGEXT}"
      THISLOGFILE: "${LOGDIRLOC}/${LOGSDIRNAME}/${LOGBASE}-${THISCOMMAND}-${CHANGELOGBASE}-${CHANGELOGEXTRA}.${CHANGELOGEXT}.${LOGEXTENSION}"
      CMDARGS: "--changeset-author=mmc --changeset-id=create-drinks --changeset-path=changelog.mdc-cafe.sql  --force"

      
    actions:

      #
      # Run the update then rollbackcount
      #

      - type: shell
        command: liquibase update --changelogfile="${CHANGELOGFILE}"        
      - type: shell
        command: liquibase --loglevel="${THISLOGLEVEL}" rollbackonechangeset ${CMDARGS} --changelogfile="${CHANGELOGFILE}" --log-file="${THISLOGFILE}"        
          
  ##############################################################


  ## A stage of actions. 
  #MakeLogFile02:
    ## set up vars for property substitution in THIS stage only
    #stageVariables:
    #  CHANGELOGEXTRA: "cafe-cropped"
    #  CHANGELOGEXT: "sql"
    #  CHANGELOGFILE: "${CHANGELOGBASE}-${CHANGELOGEXTRA}.${CHANGELOGEXT}"
    #  THISLOGFILE: "${LOGDIRLOC}/${LOGSDIRNAME}/${LOGBASE}-${THISCOMMAND}-${CHANGELOGBASE}-${CHANGELOGEXTRA}.${CHANGELOGEXT}.${LOGEXTENSION}"
    #  CMDARGS: "--deployment-id=9942428834  --force"

      
    #actions:

      #
      # THESE NEED TO BE RUN MANUALLY AS WE DONT KNOW DEPLOYMENT ID
      #

    #    manually run: liquibase update --changelogfile=changelog.mdc-cafe-cropped.sql
    #    manually run: liquibase history 
    #    then: get the deploymentid from the history output             
    #    manually run: liquibase --loglevel=INFO rollbackoneupdate --deployment-id=<INSERTDEPLOYMENTID --force --log-file=allcmds-INFO-rollbackoneupdate-changelog.mdc-cafe.sql.log --changelogfile=changelog.mdc-cafe-cropped.sql
          
  ##############################################################





## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.






endStage:
  actions:
    - type: liquibase
      command: history
      
    - type: liquibase
      command: dropall
      
      