##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########


## Set up some global variables for property substitution in ANY stage
globalVariables:
  THISCOMMAND: "diff"
  THISLOGLEVEL: "INFO"
  LOGSDIRNAME: "mdclogfiles"
  LOGDIRLOC: "."  
  LOGBASE: "allcmds-${THISLOGLEVEL}"
  LOGEXTENSION: "log"
  CHANGELOGBASE: "changelog.mdc"
  TARGETURL: "jdbc:h2:tcp://localhost:9090/mem:dev"
  SOURCEURL: "jdbc:h2:tcp://localhost:9090/mem:integration"

# do some stages 
stages:


  ## A stage of actions. 
  MakeLogFile01:
    ## set up vars for property substitution in THIS stage only
    stageVariables:
      TARGETCHANGELOG: "${CHANGELOGBASE}-cafe.sql"
      SOURCECHANGELOG: "${CHANGELOGBASE}-cafe-cropped.sql"
      THISLOGFILE: "${LOGDIRLOC}/${LOGSDIRNAME}/${LOGBASE}-${THISCOMMAND}-cafesql-diff-cafecropped.${LOGEXTENSION}"

      
    actions:

      #
      # Run the update then rollbackcount
      #
      - type: shell
        command: liquibase update --changelogfile="${TARGETCHANGELOG}" --url="${TARGETURL}"
      - type: shell
        command: liquibase update --changelogfile="${SOURCECHANGELOG}" --url="${SOURCEURL}"
      - type: shell
        command: liquibase --loglevel="${THISLOGLEVEL}" ${THISCOMMAND} --url="${TARGETURL}" --reference-url="${SOURCEURL}" --log-file="${THISLOGFILE}"        
          
  ##############################################################


  ## A stage of actions. 
  MakeLogFile02:
    ## set up vars for property substitution in THIS stage only
    stageVariables:
      TARGETCHANGELOG: "${CHANGELOGBASE}-cafe.sql"
      SOURCECHANGELOG: "${CHANGELOGBASE}-somename.sql"
      THISLOGFILE: "${LOGDIRLOC}/${LOGSDIRNAME}/${LOGBASE}-${THISCOMMAND}-cafesql-diff-somename.${LOGEXTENSION}"
      
    actions:

      #
      # Run the update then rollbackcount
      #
      - type: shell
        command: liquibase update --changelogfile="${TARGETCHANGELOG}" --url="${TARGETURL}"
      - type: shell
        command: liquibase update --changelogfile="${SOURCECHANGELOG}" --url="${SOURCEURL}"
      - type: shell
        command: liquibase --loglevel="${THISLOGLEVEL}" ${THISCOMMAND} --url="${TARGETURL}" --reference-url="${SOURCEURL}" --log-file="${THISLOGFILE}"      

          
  ##############################################################
  
  
  ## A stage of actions. 
  MakeLogFile03:
    ## set up vars for property substitution in THIS stage only
    stageVariables:
      TARGETCHANGELOG: "${CHANGELOGBASE}-cafe.sql"
      SOURCECHANGELOG: "${CHANGELOGBASE}-03.sql"
      THISLOGFILE: "${LOGDIRLOC}/${LOGSDIRNAME}/${LOGBASE}-${THISCOMMAND}-cafesql-diff-03.${LOGEXTENSION}"
      
    actions:

      #
      # Run the update then rollbackcount
      #
      - type: shell
        command: liquibase update --changelogfile="${TARGETCHANGELOG}" --url="${TARGETURL}"
      - type: shell
        command: liquibase update --changelogfile="${SOURCECHANGELOG}" --url="${SOURCEURL}"
      - type: shell
        command: liquibase --loglevel="${THISLOGLEVEL}" ${THISCOMMAND} --url="${TARGETURL}" --reference-url="${SOURCEURL}" --log-file="${THISLOGFILE}" 


       

          
  ##############################################################  



  ## A stage of actions. 
  MakeLogFile04:
    ## set up vars for property substitution in THIS stage only
    stageVariables:
      TARGETCHANGELOG: "${CHANGELOGBASE}-cafe.sql"
      SOURCECHANGELOG: "${CHANGELOGBASE}-04-errors.xml"
      THISLOGFILE: "${LOGDIRLOC}/${LOGSDIRNAME}/${LOGBASE}-${THISCOMMAND}-cafesql-diff-04errors.${LOGEXTENSION}"
      
    actions:

      #
      # Run the update then rollbackcount
      #
      - type: shell
        command: liquibase update --changelogfile="${TARGETCHANGELOG}" --url="${TARGETURL}"
      - type: shell
        command: liquibase update --changelogfile="${SOURCECHANGELOG}" --url="${SOURCEURL}"
      - type: shell
        command: liquibase --loglevel="${THISLOGLEVEL}" ${THISCOMMAND} --url="${TARGETURL}" --reference-url="${SOURCEURL}" --log-file="${THISLOGFILE}"      

          
  ##############################################################  


  ## A stage of actions. 
  MakeLogFile05:
    ## set up vars for property substitution in THIS stage only
    stageVariables:
      TARGETCHANGELOG: "${CHANGELOGBASE}-cafe.sql"
      SOURCECHANGELOG: "${CHANGELOGBASE}-recordstore.sql"
      THISLOGFILE: "${LOGDIRLOC}/${LOGSDIRNAME}/${LOGBASE}-${THISCOMMAND}-cafesql-diff-recordstore.${LOGEXTENSION}"
      
    actions:

      #
      # Run the update then rollbackcount
      #
      - type: shell
        command: liquibase update --changelogfile="${TARGETCHANGELOG}" --url="${TARGETURL}"
      - type: shell
        command: liquibase update --changelogfile="${SOURCECHANGELOG}" --url="${SOURCEURL}"
      - type: shell
        command: liquibase --loglevel="${THISLOGLEVEL}" ${THISCOMMAND} --url="${TARGETURL}" --reference-url="${SOURCEURL}" --log-file="${THISLOGFILE}"  





## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history
      
    - type: liquibase
      command: dropall
      
      